services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fastapi-web"
    ports:
      - "8000:8000"
    # Override the default command from the Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - var.env
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload

  redis:
    image: redis:latest
    container_name: "fastapi-redis"
    expose:
      - "6379"
    # Override the default Redis command to require a password
    command: ["redis-server", "--requirepass", "myredispass"]